;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/song_menu.aks
;;;; Generation time: Wed 01 Nov 2023 06:11:27 PM CET
;;;;

;;;; Song 'song_menu' metadata constants
song_menu_address = 0x0040
song_menu_size    = 334
song_menu_end     = 0x18d

;;;; Song 'song_menu' declaration
.globl _song_menu
