///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/song_menu.aks
<<<<<<< HEAD
/// Generation time: Wed 25 Oct 2023 07:37:24 PM CEST
=======
/// Generation time: mié 25 oct 2023 19:48:14 CEST
>>>>>>> ea46aac6dab4673218383bf14b865a1cedaa879c
///

/// Song 'song_menu' metadata macros
#define song_menu_address  0x0040
#define song_menu_size     330
#define song_menu_end      0x189

/// Song 'song_menu' array declaration
extern void song_menu[song_menu_size];
