;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/song_play.aks
;;;; Generation time: Wed 01 Nov 2023 06:11:26 PM CET
;;;;

;;;; Song 'song_play' metadata constants
song_play_address = 0x018e
song_play_size    = 340
song_play_end     = 0x2e1

;;;; Song 'song_play' declaration
.globl _song_play
