///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/song_menu.aks
/// Generation time: Wed 25 Oct 2023 08:06:04 PM CEST
///

/// Song 'song_menu' metadata macros
#define song_menu_address  0x0040
#define song_menu_size     330
#define song_menu_end      0x189

/// Song 'song_menu' array declaration
extern void song_menu[song_menu_size];
