;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/song_play.aks
;;;; Generation time: Thu 02 Nov 2023 11:38:37 AM CET
;;;;

;;;; Song 'song_play' metadata constants
song_play_address = 0x018e
song_play_size    = 544
song_play_end     = 0x3ad

;;;; Song 'song_play' declaration
.globl _song_play
