;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/song_play.aks
;;;; Generation time: mié 01 nov 2023 18:12:43 CET
;;;;

;;;; Song 'song_play' metadata constants
song_play_address = 0x0176
song_play_size    = 334
song_play_end     = 0x2c3

;;;; Song 'song_play' declaration
.globl _song_play
